[default]
address = "127.0.0.1"
port = 8200
workers = 1
max_blocking = 12

[default.limits]
form = "200 MiB"
data-form = "200 MiB"
file = "200 MiB"
string = "10 MiB"
bytes = "10 MiB"
json = "10 MiB"
msgpack = "10 MiB"

[default.databases]
mysql_db = { url = "mysql://root:root@db:3306/test" }